name: Build & Push on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: adk
            file: Dockerfile.agent
          - name: ui
            file: Dockerfile.ui

    steps:
      - name: Checkout (release commit)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up QEMU (optional for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH }}

      - name: Build & Push (${{ matrix.name }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.name }}-latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.name }}-${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
