name: "Release"

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - main

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install uv and set up Python"
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: "Install dependencies"
        run: uv sync --group dev

      - name: "Run Semantic Release"
        env:
            GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: uv run semantic-release version